name:                Sat2
version:             0.1.0.0
github:              "albertojcalle/Sat2"
license:             GPL-3
author:              "Alberto J Calle Martinez"
maintainer:          "48741642+albertojcalle@users.noreply.github.com"
copyright:           "2021 Alberto J Calle Martinez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:  2 sat linear solver
category:  Logic

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: 2-sat linear time solver implementing the Aspvall, Plass and Tarjan algorithm in Haskell. Please see the README on GitHub at <https://github.com/albertojcalle/Sat2#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mios
#- minisat
- filepath
- directory
- MonadRandom
- extra
- QuickCheck
- hspec
- timeit

library:
  source-dirs: src

executables:
  Sat2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Sat2
    when:
    - condition: false
      other-modules: Paths_Sat2
tests:
  Sat2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Sat2
benchmarks:
  Sat2-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - criterion
      - Sat2
#    benchmark-opts:
#      benchmark-arguments: "--output bench.html"
#    benchmark-arguments: 
#    - -output bench.html
#stack bench --benchmark-arguments "--output bench.html"