name:                2sat
version:             0.1.0.0
github:              "albertojcalle/2sat"
license:             GPL-3.0
author:              "Alberto J Calle Martinez"
maintainer:          "48741642+albertojcalle@users.noreply.github.com"
copyright:           "2021 Alberto J Calle Martinez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/albertojcalle/2sat#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mios
#- minisat
- filepath
- directory
- MonadRandom
- extra
- QuickCheck
- hspec
- timeit

library:
  source-dirs: src

executables:
  2sat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 2sat
    when:
    - condition: false
      other-modules: Paths_2sat
tests:
  2sat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 2sat
benchmarks:
  2sat-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - criterion
      - 2sat
#    benchmark-opts:
#      benchmark-arguments: "--output bench.html"
#    benchmark-arguments: 
#    - -output bench.html
#stack bench --benchmark-arguments "--output bench.html"